name: Prod deployment from Github to AWS
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Build client Prod Dockerfile
        run: docker build -t ${{secrets.DOCKER_USER}}/docker-client-prod -f ./client/Dockerfile .

      - name: Build worker Prod Dockerfile
        run: docker build -t ${{secrets.DOCKER_USER}}/docker-worker-prod -f ./worker/Dockerfile .

      - name: Build server Prod Dockerfile
        run: docker build -t ${{secrets.DOCKER_USER}}/docker-server-prod -f ./server/Dockerfile .

      - name: Build nginx Prod Dockerfile
        run: docker build -t ${{secrets.DOCKER_USER}}/docker-nginx-prod -f ./nginx/Dockerfile .

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.ACCESS_TOKEN}}

      - name: Push worker image to DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/docker-worker-prod

      - name: Push client image to DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/docker-client-prod

      - name: Push server image to DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/docker-server-prod

      - name: Push nginx image to DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/docker-nginx-prod
