name: Prod deployment from Github to AWS
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Build client Prod Dockerfile
        run: docker build -t ${{secrets.DOCKER_USER}}/docker-client-prod -f ./client/Dockerfile .

      - name: Build worker Prod Dockerfile
        run: docker build -t ${{secrets.DOCKER_USER}}/docker-worker-prod -f ./worker/Dockerfile .

      - name: Build server Prod Dockerfile
        run: docker build -t ${{secrets.DOCKER_USER}}/docker-server-prod -f ./server/Dockerfile .

      - name: Build nginx Prod Dockerfile
        run: docker build -t ${{secrets.DOCKER_USER}}/docker-nginx-prod -f ./nginx/Dockerfile .

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.ACCESS_TOKEN}}

      - name: Push worker image to DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/docker-worker-prod

      - name: Push client image to DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/docker-client-prod

      - name: Push server image to DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/docker-server-prod

      - name: Push nginx image to DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/docker-nginx-prod

      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: '${{ steps.current-time.outputs.time }}'
          replace-with: '-'
          flags: 'g'

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          region: ap-south-1
          application_name: docker-multi-react
          environment_name: Dockermultireact-env
          version_label: docker-react-${{ steps.format-time.outputs.replaced }}
          deployment_package: deploy.zip
